### ISSUE TITLE
Config issue: nested node saves twice???

### ISSUE THREAD

**Issue by fromgate** [Nukkit/Nukkit#169]
Hello!
I'm trying to save config file. 
```java
    private void save(){
        this.getDataFolder().mkdirs();
        File f = new File(this.getDataFolder(),"config.yml");
        if (f.exists()) f.delete();
        Config cfg = new Config(f,Config.YAML);
        cfg.setNested("database.url",this.dbUrl);
        cfg.save();
    }
```

And here is result:
```yaml
database:
  url: jdbc:sqlite:c:\test\test.db
database.url: jdbc:sqlite:c:\test\test.db
```
Is it bug? Or I'm doing something wrong?
