### ISSUE TITLE
Depending on plugins 

### ISSUE THREAD

**Issue by imjack** [Nukkit/Nukkit#173]
Adding depend in the plugin.yml Doesn't seem to make much difference
23:21:20 [INFO] Enabling MadRegions v1.0.0
23:21:20 [INFO] [MadRegions] MadRegion is loading....
23:21:20 [INFO] Enabling MadPerms v1.0.0
23:21:20 [INFO] [MadPerms] MadPerms is loading....

In my MadRegions plugin.yml
```` yaml
name: MadRegions
main: me.imjack.region.Main
version: "1.0.0"
api: ["1.0.0"]
depend:
- MadPerms
````
