### ISSUE TITLE
Bug with alias

### ISSUE THREAD

**Issue by ICHx** [Nukkit/Nukkit#177]
Steps
--
1. Opened nano to edit  nukkit.yml
2. Added the following aliases:
gm: [gamemode]
sws: [setworldspawn]
,etc
3. Start server by using java -jar xxx.jar -Xmx512m -Xms128m
4. Type the designated aliases in console and clients

Output
--
[INFO] 未知的指令。請使用 /help 來顯示指令列表。
indicating that the alias function is not working as expected.

I love this project :) so much, thx y'all.

**Comment by MagicDroidX** [comment]
Cannot reproduce this.
My `nukkit.yml`:
```
aliases:
 #指令别称 [目前不可用]
 #例：
 gm: [gamemode]
 v: version
 #showtheversion: version
 #savestop: [save-all, stop]
```

It works well.
