### ISSUE TITLE
setNested removes other subkeys.

### ISSUE THREAD

**Issue by ProjectInfinity** [Nukkit/Nukkit#181]
Prior to saving:
```
api:
  key: ''
  port: 443
  url: 'api.leet.cc'
```

Then saving doing 
```
this.plugin.getConfig().setNested("api.key", jsonObject.get("token").toString());
this.plugin.saveConfig();
```

Results in 
```
api:
  key: ZmMwZGZjNGI1ZTlhNDBhNjhlODg1ZThkNTcyYmRiM2Q=
api.key: ZmMwZGZjNGI1ZTlhNDBhNjhlODg1ZThkNTcyYmRiM2Q=
```
